#! /bin/bash

cp ~/.vimrc vim/
cp -r ~/.vim/snippets vim/
cp ~/.git* git/
cp ~/.tmux.conf tmux/
cp ~/.agignore .

cp ~/.zshrc zsh/
cp ~/.zsh-aliases zsh/
cp ~/.zsh-functions zsh/

cp ~/iCloud/mac-setup/*.sh setup/
